### ISSUE TITLE
doesn't work with ofGLProgrammableRenderer

### ISSUE THREAD

**Issue by julapy** [elliotwoods/ofxGrabCam#8]
when enabling the ofGLProgrammableRenderer, ofxGramCam only partially works.

````
int main( ){

    ofGLFWWindowSettings windowSettings;
    windowSettings.setGLVersion(4, 1);
    windowSettings.width = 1024;
    windowSettings.height = 768;
    windowSettings.windowMode = OF_WINDOW;
    
    ofCreateWindow(windowSettings);
    
    ofRunApp( new testApp());

}
````

cursor functionality does not work.

looks like gl calls need to go through OF API for this addon to work on fixed pipeline and programmable.

**Comment by elliotwoods** [comment]
can you explain what doesn’t work?
my guess is that it doesn’t grab the depth value correctly
is this what you are experiencing?


screenshot would be great

**Comment by julapy** [comment]
hey @elliotwoods, thats right, the depth value is always coming back as (0, 0, 0) and so the cursor only sticks to that point.

**Comment by elliotwoods** [comment]
any suggested fix? ;)

**Comment by julapy** [comment]
hey,
i only had a brief look...
but it seemed that the instead of using raw gl call, the addon needs to call the OF api for the ofGLProgrammableRenderer to work correctly.
thats as much as i can look into it... flat out with other work atm :/

**Comment by elliotwoods** [comment]
ofGLFWWindowSettings doesn't exist in my oF, is this something new with 0.9.0?

**Comment by elliotwoods** [comment]
edit : i'm on 0.8.4

**Comment by julapy** [comment]
yeah thats the new method for setting up a window with the latest master.

i think the old method for enabling the programmable renderer is,

````
int main() {
    ofSetCurrentRenderer(ofGLProgrammableRenderer::TYPE);
    ofSetupOpenGL(1024, 768, OF_WINDOW);
    ofRunApp(new ofApp());
}
````

i pulled that out of an older app which i think was built against 084 or there abouts.

**Comment by elliotwoods** [comment]
hey
i'm going to put this on ice for a while until either i'm on 0.9.0 or using
programmable renderer
also i'm working on ideas for a v2.0 of ofxGrabCam (orthogonal views,
keyboard shortcuts, more reliable mouseing)
be great to hear any ideas

**Comment by elliotwoods** [comment]
i'm on 0.9.0 now and am getting crashes sometimes when using ofxGrabCam with it so i'm actively looking to rewrite now. looking into it!

**Comment by elliotwoods** [comment]
ok i've rewritten the existing functionality and it works in the programmable renderer
![image](https://cloud.githubusercontent.com/assets/328294/9085440/ac0a8f62-3bb7-11e5-833c-d30d64b78a32.png)

this is pushed to master
sorry about the incredibly long wait!

i noticed that when you initialise the window this way (rather than the previous way) that it causes the pixels to draw 1:1 on highdpi screens (i.e. ignores highdpi settings. testing on windows).
this is curious because i didn't know there was any way to turn highdpi on/off in windows.

**Comment by julapy** [comment]
awesome! looks forward to using it :)
